version: '3.8'

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - ha_network

  nginx2:
    image: nginx:latest
    container_name: nginx2
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - ha_network

  keepalived_master:
    image: osixia/keepalived:latest
    container_name: keepalived_master
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./keepalived/keepalived_master.conf:/etc/keepalived/keepalived.conf:ro
    networks:
      - ha_network
    depends_on:
      - nginx1
    command: --loglevel debug

  keepalived_backup:
    image: osixia/keepalived:latest
    container_name: keepalived_backup
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./keepalived/keepalived_backup.conf:/etc/keepalived/keepalived.conf:ro
    networks:
      - ha_network
    depends_on:
      - nginx2
    command: --loglevel debug

networks:
  ha_network:
    driver: bridge
