version: '3.8'

services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - ha_network

  nginx2:
    image: nginx:latest
    container_name: nginx2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - ha_network

  keepalived_master:
    image: osixia/keepalived:latest
    container_name: keepalived_master
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./keepalived/keepalived_master.conf:/container/service/keepalived/assets/keepalived.conf:ro
    networks:
      - ha_network
    depends_on:
      - nginx1

  keepalived_backup:
    image: osixia/keepalived:latest
    container_name: keepalived_backup
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    volumes:
      - ./keepalived/keepalived_backup.conf:/container/service/keepalived/assets/keepalived.conf:ro
    networks:
      - ha_network
    depends_on:
      - nginx2

networks:
  ha_network:
    driver: bridge
